### ISSUE TITLE
ImportError: No module named inc.algorithms

### ISSUE THREAD

**Issue by Giando** [PlumLulz/hashes.com-cli#3]
After commit dd20492665f23cd2f2cc34b5e8b0d7d2cec0f083 it starts up, but:

```
$ python hashes.py 
Traceback (most recent call last):
  File "hashes.py", line 17, in <module>
    from inc.algorithms import validalgs
ImportError: No module named inc.algorithms
```

**Comment by PlumLulz** [comment]
What version of Python are you on and what OS?

**Comment by Giando** [comment]
```
$ python --version
Python 2.7.16
$ python3 --version
Python 3.7.3
$ uname -a
Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
```

**Comment by PlumLulz** [comment]
Make sure you are using Python3 to run this script. I would try and do a fresh install. 

git clone https://github.com/PlumLulz/hashes.com-cli.git hashes-cli

cd hashes-cli

pip3 install -r requirements.txt

python3 hashes.py

**Comment by PlumLulz** [comment]
Were you able to get this issue resolved?

**Comment by PlumLulz** [comment]
> ```
> $ python --version
> Python 2.7.16
> $ python3 --version
> Python 3.7.3
> $ uname -a
> Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
> $ lsb_release -a
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 10 (buster)
> ```
Were you able to get this issue resolved?

**Comment by Giando** [comment]
> Make sure you are using Python3 to run this script. I would try and do a fresh install.
> ```
> git clone https://github.com/PlumLulz/hashes.com-cli.git hashes-cli
> 
> cd hashes-cli
> 
> pip3 install -r requirements.txt
> 
> python3 hashes.py
> ```

Yes, with Python3 it works, it's also written in [README](https://github.com/PlumLulz/hashes.com-cli/blob/master/README.md).
Sorry for the oversight.

Thank you very much,
best regards.
